# Generated by Django 3.0.4 on 2020-03-21 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200320_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutusimage',
            name='aboutus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Aboutus'),
        ),
        migrations.AlterField(
            model_name='aboutusimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='aboutusparagrap',
            name='aboutus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Aboutus'),
        ),
        migrations.AlterField(
            model_name='aboutusparagrap',
            name='paragrap',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Home'),
        ),
        migrations.AlterField(
            model_name='galleryprojects',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Projects'),
        ),
        migrations.AlterField(
            model_name='infocontactus',
            name='contactus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Contactus'),
        ),
        migrations.AlterField(
            model_name='mapcontactus',
            name='contactus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Contactus'),
        ),
        migrations.AlterField(
            model_name='navbarhome',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Home'),
        ),
        migrations.AlterField(
            model_name='servicesnavbar',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Services'),
        ),
    ]
