# Generated by Django 3.0.4 on 2020-03-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200321_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name_plural': 'B-About Us'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'D-Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name_plural': 'F-Footer'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': 'A-Home'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'E-Projects'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'C-Services'},
        ),
        migrations.AlterField(
            model_name='aboutusimage',
            name='aboutus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Aboutus'),
        ),
        migrations.AlterField(
            model_name='aboutusparagrap',
            name='aboutus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Aboutus'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Home'),
        ),
        migrations.AlterField(
            model_name='galleryprojects',
            name='projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Projects'),
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='infocontactus',
            name='contactus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Contactus'),
        ),
        migrations.AlterField(
            model_name='mapcontactus',
            name='contactus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Contactus'),
        ),
        migrations.AlterField(
            model_name='navbarhome',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Home'),
        ),
        migrations.AlterField(
            model_name='servicesnavbar',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Services'),
        ),
        migrations.CreateModel(
            name='HomeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=250)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.Home')),
            ],
        ),
    ]
